baseURL: https://shalemrajkumar.github.io
title: <raj.sh'log>
theme: PaperMod
env: production

frontmatter:
  date:
    - :filename
    - :default
  publishDate:
    - :filename
    - :default


permalinks:
  blog: blog/:year/:month/:day/:slug/

params:
  defaultTheme: auto
  showReadingTime: true
  showPostNavLinks: true
  showCodeCopyButtons: true
  showFullTextinRSS: true
  showShareButtons: true
  math: true

  socialIcons:
    - name: github
      url: https://github.com/shalemrajkumar
    - name: linkedin
      url: https://www.linkedin.com/in/shalemrajkumar/
    - name: twitter
      url: https://twitter.com/shalemrajkumar

  profileMode:
    enabled: true

menu:

  main:
    - weight: 1
      identifier: bio
      name: Bio
      title: bio
      url: /bio/

    - weight: 2
      identifier: research
      name: Research
      title: Research
      url: /research/

    - weight: 3
      identifier: blog
      name: Blog
      title: blog
      url: /blog/

    - weight: 4
      identifier: whats up!
      name: Whats up!
      title: what's up!
      url: /wip/

    - weight: 5
      identifier: archives
      name: Archive
      title: archives
      url: /archives/

    - weight: 6
      identifier: search
      name: Search
      title: search
      url: /search/

    - weight: 7
      identifier: tags
      name: Tags
      title: tags
      url: /tags/

markup:
  goldmark:
    renderer:
      unsafe: true
            


# search functionality      

outputs:
  home:
    - HTML
    - RSS
    - JSON

# search - fusejs
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

# archive page
ShowAllPagesInArchive: true
