baseURL = "https://shalemrajkumar.github.io"
title = "<raj.sh'log>"
theme = "PaperMod"
env = "production"

# Infer my posts' dates from filename, like Jekyll
[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename", ":default"]

# Use the same URL structure as my Jekyll blog
[permalinks]
blog = "blog/:year/:month/:day/:slug/"

[params]
defaultTheme = "auto"
showReadingTime = true
showPostNavLinks = true
showCodeCopyButtons = true
showFullTextinRSS = true
showShareButtons = true

# Shown on the home page
socialIcons = [
  { name = "github", url = "https://github.com/shalemrajkumar" },
  #{ name = "mastodon", url = "https://mastodon.social/@" },
  #{ name = "stackoverflow", url = "https://stackoverflow.com/users/" },
  { name = "linkedin", url = "https://www.linkedin.com/in/shalemrajkumar/" },
  #{ name = "Python Discourse", url = "https://discuss.python.org/u//summary" },
  #{ name = "gitlab", url = "https://gitlab.com/" },
  #{ name = "keybase", url = "https://www.keybase.io/" },
  #{ name = "reddit", url = "https://www.reddit.com/user/" },
  { name = "twitter", url = "https://twitter.com/shalemrajkumar" },
  #{ name = "hackerrank", url = "https://www.hackerrank.com/profile/"},
]

# Configure the home page
[params.profileMode]
enabled = true # I override the index_profile.html file.

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
# url = "/about/"
url = "/wip/"


[[menu.main]]
weight = 2
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog/"

[[menu.main]]
weight = 3
identifier = "open_docs"
name = "open docs"
title = "open docs"
# url = "/open_docs/"
url = "/wip/"

[[menu.main]]
weight = 4
identifier = "whats up!"
name = "whats up!"
title = "What's up!"
# url = "/whats_up/"
url = "/wip/"

[[menu.main]]
weight = 5
identifier = "archive"
name = "archive"
title = "archive"
# url = "/archive/"
url = "/wip/"

[[menu.main]]
weight = 6
identifier = "search"
name = "search"
title = "search"
# url = "/search/"
url = "/wip/"

[[menu.main]]
weight = 7
identifier = "tags"
name = "tags"
title = "tags"
url = "/tags/"

# Allow HTML in my content pages.
[markup.goldmark.renderer]
unsafe = true
